package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessageConfig<M extends BaseMessageConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setIsSmsEnabled(java.lang.Boolean isSmsEnabled) {
		set("isSmsEnabled", isSmsEnabled);
		return (M)this;
	}
	
	public java.lang.Boolean getIsSmsEnabled() {
		return get("isSmsEnabled");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setSmsCode(java.lang.String smsCode) {
		set("smsCode", smsCode);
		return (M)this;
	}
	
	public java.lang.String getSmsCode() {
		return getStr("smsCode");
	}

}
